{
	"version": 1497272269,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/blocochao-sheet0.png",
		"images/blocoheroi-sheet0.png",
		"images/lagarta-sheet0.png",
		"images/sensor-sheet0.png",
		"images/fogueira-sheet0.png",
		"images/passaro-sheet0.png",
		"images/vidavazio-sheet0.png",
		"images/tilemap.png",
		"images/sprite-sheet0.png",
		"images/coingold-sheet0.png",
		"images/player_idle-sheet0.png",
		"images/player_idle-sheet1.png",
		"images/player_idle-sheet2.png",
		"media/phasejump1 (online-audio-converter.com).ogg",
		"media/powerup9 (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}